// src/store/actionTypes.js
export const SET_CART_LIST = "SET_CART_LIST";
export const SET_PAYMENT = "SET_PAYMENT";
export const SET_ADDRESS = "SET_ADDRESS";
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_PRODUCT_COUNT = 'INCREMENT_PRODUCT_COUNT';
export const DECREMENT_PRODUCT_COUNT = 'DECREMENT_PRODUCT_COUNT';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const TOGGLE_PRODUCT_CHECKED = 'TOGGLE_PRODUCT_CHECKED';
export const FETCH_ADDRESSES_SUCCESS = "FETCH_ADDRESSES_SUCCESS";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';
export const FETCH_CART_DETAILS_SUCCESS = 'FETCH_CART_DETAILS_SUCCESS';
export const RESET_CART = 'RESET_CART';

